services:
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${SERVICE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${SERVICE_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/mongodb
volumes:
  mongodb: