services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: hits
    ports:
      - 5432:5432
    volumes:
      - postgres:/data/postgres
volumes:
  postgres:
