services:
  redis:
    image: redis:7.2.0-alpine
    environment:
      REDIS_USERNAME: ${SERVICE_USERNAME}
      REDIS_PASSWORD: ${SERVICE_PASSWORD}
    ports:
      - "6379:6379"
    networks:
      - redis
    volumes:
      - redis:/data/redis
    restart: unless-stopped
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: tyiu
      POSTGRES_USER: ${SERVICE_USERNAME}
      POSTGRES_PASSWORD: ${SERVICE_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER= ${SERVICE_USERNAME}
      - RABBITMQ_DEFAULT_PASS= ${SERVICE_PASSWORD}
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
networks:
  postgres:
    driver: bridge
  redis:
    driver: bridge
volumes:
  postgres:
  redis:
  rabbitmq: