logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
postgres:
  url: postgresql://localhost:5432/hits
file:
  path:
    avatar: "./src/main/resources/files/avatars/"
    idea: "./src/main/resources/files/ideas/"
spring:
  data:
    r2dbc:
      repositories:
        enabled: false
  r2dbc:
    pool:
      enabled: true
      initial-size: 10
      max-idle-time: 1m
      max-size: 30
    url: r2dbc:${postgres.url}
    username: admin
    password: admin
  flyway:
    url: jdbc:${postgres.url}
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true
    locations: classpath:db/migration
    enabled: true
    validate-on-migrate: true
  rsocket:
    server:
      transport: websocket
      mapping-path: /rs
  output:
    ansi:
      enabled: ALWAYS
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_LOGIN}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 80
jwt:
  secret: SDJKFKLSDJFSEOPFJSKJCKZXNOIWU289737494723094823