spring:
  rsocket:
    server:
      port: 7000
      transport: websocket
      mapping-path: /rs
  data:
    mongodb:
      uri: mongodb://${SERVICE_USERNAME}:${SERVICE_PASSWORD}@mongodb:27017/admin
    redis:
      repositories:
        enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_LOGIN}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  redis:
    host: redis
    port: 6379
    password: ${SERVICE_PASSWORD}
server:
  port: 3000
jwt:
  secret: ${JWT_SECRET}
