spring:
  rsocket:
    server:
      port: 7000
      transport: websocket
      mapping-path: /rs
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/admin
    redis:
      repositories:
        enabled: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_LOGIN}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  redis:
    host: localhost
    port: 6379
    password: admin
server:
  port: 3000
jwt:
  secret: SDJKFKLSDJFSEOPFJSKJCKZXNOIWU289737494723094823
