logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
postgres:
  url: postgresql://postgres:5432/hits
file:
  path:
    avatar: "./src/main/resources/avatars/"
spring:
  data:
    r2dbc:
      repositories:
        enabled: false
  r2dbc:
    pool:
      enabled: true
      initial-size: 10
      max-idle-time: 1m
      max-size: 30
    url: r2dbc:${postgres.url}
    username: ${SERVICE_USERNAME}
    password: ${SERVICE_PASSWORD}
  flyway:
    url: jdbc:${postgres.url}
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true
    locations: classpath:db/migration
    enabled: true
    validate-on-migrate: true
  rsocket:
    server:
      port: 7000
      transport: websocket
      mapping-path: /rs
  mail:
    host: smtp.gmail.com
    port: 465
    username: ${MAIL_LOGIN}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: false
server:
  port: 80
jwt:
  secret: ${JWT_SECRET}
