name: DEPLOY

on: workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Build JAR file
        run: ./gradlew clean build

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SERVER_HOST}}
          username: ${{secrets.SERVER_USERNAME}}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/lex/hits/
            git pull origin main
            ./gradlew build
            docker build
            docker compose up -d
