name: DEPLOY

on: workflow_dispatch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      MAIL_LOGIN: ${{ secrets.MAIL_LOGIN }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      SERVICE_USERNAME: ${{ secrets.SERVICE_USERNAME }}
      SERVICE_PASSWORD: ${{ secrets.SERVICE_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build containers
        run: |
          docker-compose -f docker-compose-prod.yml up -d

      - name: Build JAR file
        run: ./gradlew -PspringProfile=prod build -x test

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: lexunok/hits:latest
