name: Tests

on:
  push:
    branches:
      - tests

jobs:
  run_tests:
    runs-on: ubuntu-latest
    env:
      MAIL_LOGIN: ${{ secrets.MAIL_LOGIN }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: |
            ~/.docker
          key: ${{ runner.os }}-docker-${{ hashFiles('docker-compose.yml','docker-compose-test.yml') }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build containers
        run: |
          docker-compose up -d

      - name: Build JAR file
        run: ./gradlew -PspringProfile=test build -x test

      - name: Run tests
        run: ./gradlew test -Pprofile=test
