name: TESTS

on: workflow_dispatch

jobs:
  run_tests:
    runs-on: ubuntu-latest
    env:
      MAIL_LOGIN: ${{ secrets.MAIL_LOGIN }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build containers
        run: |
          docker-compose up -d

      - name: Build JAR file
        run: ./gradlew -PspringProfile=prod build

